name: Create Enhancement Issue (ja)
description: Enchancement Issue Template (ja)
labels: [ "enhancement", "bug"] # 
body:
  - type: markdown
    attributes:
      value: |
        実装の概要や目的について、できるだけ詳細に記述してください
  - type: input
    id: overview
    attributes:
      label: 概要
      description: |
        この実装の概要について記載してください
  - type: textarea
    id: purpose
    attributes:
      label: 目的
      description: |
        このIssueの目的や、解決することでユーザが実現できるようになることを記載してください
  - type: textarea
    id: task
    attributes:
      label: タスク
      description: |
        このIssueを解決するために必要な作業を入力してください
      value: |
        - [ ] XXX
  - type: markdown
    attributes:
      value: "## 自動化設定"
  - type: dropdown
    id: is-create-branch
    attributes:
      label: Issueの作成と同時にBranchを作成しますか？
      options:
        - はい、作成します
        - いいえ、作成しません
    validations:
      required: true
  - type: input
    id: branch-name
    attributes:
      label: Branch名
      description: |
        Issueに関連付けられるBranchの名前を入力してください
        実際のBranch名には、ラベルに応じた接頭辞とIssueの番号が付加されます
        Branchの命名規則は[XXX]()を参照してください
