# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Issueが作成されたときにワークフローをトリガーする
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # https://www.docswell.com/s/_n13u_/K1JG4E-2024-02-27-mierunebbq#p19
      - name: create branch
        run: |
          # labelにenhancementとbugの両方が含まれていた場合、終了する（いつか作りたい）
          # Issueのラベルを取得する
          label=$(echo $LABELS | jq -r '.[].name')
          # Prefixの生成
          if [[ $label == *"enhancement"* ]]; then
            branch_prefix="feature/"
          elif [[ $label == *"bug"* ]]; then
            branch_prefix="fix/"
          else
            branch_prefix=""
          fi

          # Issueに記載されたブランチ名を取得する
          branch_content=$(echo "$BODY" | grep -A 2 "### Branch Name" | tail -n 1)
          branch_suffix="_${NUMBER}"
          branch_name=$branch_prefix$branch_content$branch_suffix
          # Issueに関連するブランチを作成する
          gh issue develop $NUMBER --name "$branch_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ## IssueのIDを取得する
          NUMBER: ${{ github.event.issue.number }}
          ## IssueのLabelを取得する
          LABELS: ${{ toJson(github.event.issue.labels) }}
          ## bodyを取得する
          BODY: ${{ github.event.issue.body }}
          
